version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - klinika-es

  neo4j:
    image: neo4j:latest
    container_name: myneo4j
    restart: always
    ports:
      - "7474:7474" 
      - "7687:7687"  
    environment:
      NEO4J_AUTH: neo4j/password 
    volumes:
      - ./data:/data
    networks:
     - klinika-es

  klinika:
    image: klinika
    ports:
      - "8082:8082"
    build:
      context: .
    container_name: klinika
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Klinika
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - ADDITIONAL_PATH=/klinika/swagger-ui/index.html
    links:
     - redis
     - neo4j
    networks:
     - klinika-es

networks:
  klinika-es:  