version: '3.4'

volumes:
  pg_project:

services:
  Klinik:
    image: klinika
    ports:
      - "8082:8082"
    build:
      context: .
    container_name: klinika
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Klinika
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - JWT_PRIVATE_KEY=classpath:keys/private.pem
      - JWT_PUBLIC_KEY=classpath:keys/public.pem
      - ENCRYPTION_KEY=classpath:keys/encryption.key
      # https
      #- KEYSTORE=classpath:keystore/klinika.jks 
      #- SERVER_SSL_KEY-STORE=classpath:keystore/klinika.jks  
      #- SERVER_SSL_KEY-STORE-PASSWORD=
      #- SERVER_SSL_KEY-STORE-ALIAS=  
    volumes:
      - ./src/main/resources/keys:/app/keys
      - ./src/main/resources/keystore:/app/keystore
