#apache kafka with KRaft mode + app + kafka-ui
version: '3.7'

services:
  Klinik:
    image: klinika
    ports:
      - "8082:8082"
    build:
      context: .
    container_name: klinika
    depends_on:
      - broker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Klinika
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - jwt.private.key=classpath:keys/private.pem
      - jwt.public.key=classpath:keys/public.pem
      - encryption.key=classpath:keys/encryption.key
      - encryption.path=/app/keys/encryption.key
      - generate.keys.path=/app/keys
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
    volumes:
      - ./src/main/resources/keys:/app/keys
      - ./src/main/resources/keystore:/src/main/resources/keystore

  broker:
    image: apache/kafka:3.8.0
    container_name: broker
    hostname: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://broker:29092,CONTROLLER://broker:29093,EXTERNAL://0.0.0.0:9092'
      #app local
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker:29092,EXTERNAL://localhost:9092'
      #app in docker
      #KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker:29092,EXTERNAL://broker:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      #KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      #KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      #CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: always
    container_name: kafka-ui
    ports:
      - "8040:8080"  
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true' 
      KAFKA_SERVER: 'broker:9092'  
    depends_on:
      - broker