version: "3.4"
services:
  klinika:
    image: klinika
    ports:
      - "8082:8082"
    build:
      context: .
    container_name: klinika
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Klinika
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - ADDITIONAL_PATH=/klinika/swagger-ui/index.html
    networks:
      - klinika-es
networks:
  klinika-es:

