version: '3.4'

volumes:
  pg_project:

services:
  Klinik:
    image: klinika
    ports:
      - "8082:8082"
    build:
      context: .
    container_name: klinika_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Klinika
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - ADDITIONAL_PATH=/klinika/swagger-ui/index.html

