version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: myneo4j
    restart: always
    ports:
      - "7474:7474" 
      - "7687:7687"  
    environment:
      NEO4J_AUTH: neo4j/password 
    volumes:
      - ./data:/data
    networks:
     - klinika-es
networks:
  klinika-es:  