version: '3.8'
services:
# APP Klinika
  klinika:
    image: klinika
    ports:
      - "8082:8082"
    build:
      context: .
    container_name: klinika
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/Klinika
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - ADDITIONAL_PATH=/klinika/swagger-ui/index.html
      - CASSANDRA_KEYSPACE=testkeyspace
      - CASSANDRA_HOST=cassandra
    links:
     - mongodb
     - cassandra
     - redis
    networks:
      - klinika-es
#DB CASSANDRA
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_KEYSPACE=testkeyspace
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=100M
    networks:
      - klinika-es 
#DB REDIS
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - klinika-es
#DB MONGO  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - klinika-es
volumes:
  mongodb_data:

#NETWORK      
networks:
  klinika-es: