#compose app (repository) with postgres and excute backup to get data
version: '3.4'

volumes:
  pg_project:

services:
  Klinik:
    image: kirillkus/authklinik:latest
    ports:
      - "8082:8082"
    container_name: klinika
    depends_on:
      - pg_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5434/Klinika
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - JWT_PRIVATE_KEY=classpath:keys/private.pem
      - JWT_PUBLIC_KEY=classpath:keys/public.pem
      - ENCRYPTION_KEY=classpath:keys/encryption.key
    volumes:
      - ./src/main/resources/keys:/app/keys
      - ./src/main/resources/keystore:/app/keystore
  pg_db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Klinika
    volumes:
      # excute backup to get data
      - ./src/main/resources/db/backup/klinika.backup:/klinika.backup
      - ./src/main/resources/db/backup/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - ${POSTGRES_PORT:-5434}:5432