apiVersion: v1
kind: Service
metadata:
  name: klinika
  labels:
    k8s-app: klinika
spec:
  type: NodePort
  selector:
    app: klinika
  ports:
  - name: 
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klinika
  namespace: default
  labels:
    k8s-app: klinika
spec:
  template:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: klinika
    metadata:
      name: klinika
      labels:
        k8s-app: klinika
    spec:
      containers:
        - name: klinika
          image: kirillkus/app2
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/Klinika
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: none
---

kubectl expose deployment klinik --type=NodePort --port=8080